/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scene.ThemeScreen;

import javax.swing.ImageIcon;
import main.Global;
import script.posisi;

/**
 *
 * @author ryo
 */
public class introScene extends javax.swing.JFrame {

    /**
     * Creates new form introScene
     */
    
    private posisi posisiBackgroundDialog;
    private posisi posisiMC;
    private posisi posisiBoxDialog;
    private String teks;
    private posisi posisiBackgroundSurat;
    private posisi posisiLabelNama;
    
    public introScene() {
        
        // 1. Setup Ukuran & Layout Frame (Wajib paling atas)
    this.setUndecorated(true);
    initComponents();
    Global.initCeritaGame(); 
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    this.getContentPane().setLayout(null);
    
    // =========================================================================
    // SAKELAR PELINDUNG JTEXTAREA (Anti-Caret & Anti-Highlight)
    // =========================================================================
    boxDialog.setEditable(false);         // Teks tidak bisa diedit/dihapus
    boxDialog.setHighlighter(null);       // Teks tidak bisa diblok/diseleksi warna biru
    boxDialog.setFocusable(false);        // JTextArea tidak bisa menerima fokus klik mouse
    boxDialog.setCursor(null);            // Mengubah kursor [I] jadi kursor panah biasa
    boxDialog.setBackground(new java.awt.Color(0, 0, 0, 0)); // Transparan
    
    backgroundSurat.setVisible(false);
    
    // 2. Alur Inisialisasi Data Dialog
    main.Global.indeksDialog = 0;       // Mulai dari awal dialog (indeks 0)
    tampilkanDialogSekarang();            // Tampilkan teks pertama ke boxDialog
    
    // 3. Set Ukuran Komponen Secara Manual (Agar class posisi tidak salah hitung lebar)
    boxDialog.setSize(800, 250);          // Sesuaikan lebar & tinggi kotak teks game kamu
    
    // 4. Render Gambar Aset Game
    ImageIcon introSceneBackground = main.Global.backgroundIntroScene.ambilGambar(background);
    background.setIcon(introSceneBackground);
    
    ImageIcon detektif = main.Global.guwe.ambilGambar(detektifSprite);
    detektifSprite.setIcon(detektif);
    
    // 5. Inisialisasi & Eksekusi Class Posisi
    posisiMC = new script.posisi(detektifSprite);
    posisiBackgroundDialog = new script.posisi(backgroundDialog);
    posisiBoxDialog = new script.posisi(boxDialog);
    posisiBackgroundSurat = new posisi(backgroundSurat);
    posisiLabelNama = new posisi(labelNama);
    
    posisiBackgroundSurat.posisi(0, 100);
    posisiBackgroundSurat.tengahHorizontal(this);
    
    // Atur posisi posisi VN (Misal: detektif berdiri di kiri bawah)
    posisiMC.kiriBawah(this); 
    
    // Jalankan method custom bawaan kamu
    aturPosisi(); 
    
    // =========================================================================
    // FILTER KEYBOARD: Jalankan Dialog via Tombol SPACE
    // =========================================================================
    this.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_SPACE) {
                mouseClicked(null);
            }
        }
    });
    this.setFocusable(true);
    this.requestFocusInWindow();
    
  
        
    }
    
    private void aturPosisi() {
        posisiMC.posisi(0, 200);
        posisiMC.kiriBawah(this);
        
        posisiBackgroundDialog.aturSebagaiBackgroundDialog(this);
        
        posisiBoxDialog.aturSebagaiBoxDialog(this);
        
        posisiLabelNama.aturSebagaiLabelNama();
    }
    

    
    
    private void tampilkanDialogSekarang() {
    // Ambil objek Dialog dari array berdasarkan indeks saat ini
        backgroundSurat.setVisible(false);
        
        script.Dialog d = main.Global.listBriefing[main.Global.indeksDialog];

    // Pasang nama pembicara ke JLabel nama
    labelNama.setText(d.getNama());

    // Pasang isi teks ke JLabel/boxText kamu (Pakai HTML biar otomatis center & wrap)
    
        if(d.getNama().equals(Global.Vesper.getNama())) {
            backgroundSurat.setVisible(true);
        }
        boxDialog.setText(d.getTeks());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNama = new javax.swing.JLabel();
        boxDialog = new javax.swing.JTextArea();
        backgroundSurat = new javax.swing.JLabel();
        backgroundDialog = new javax.swing.JLabel();
        detektifSprite = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                introScene.this.mouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNama.setForeground(new java.awt.Color(0, 0, 0));
        labelNama.setText("dummyyyyyyyyyyyyyyyy");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 730, 200, 50));

        boxDialog.setEditable(false);
        boxDialog.setColumns(5);
        boxDialog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boxDialog.setForeground(new java.awt.Color(0, 0, 0));
        boxDialog.setRows(5);
        boxDialog.setText("\nsddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
        boxDialog.setBorder(null);
        getContentPane().add(boxDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 900, 190));

        backgroundSurat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/surat.png"))); // NOI18N
        getContentPane().add(backgroundSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 650, 530));

        backgroundDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/dialogueBox.png"))); // NOI18N
        getContentPane().add(backgroundDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 1000, 270));
        getContentPane().add(detektifSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 130, 150));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aturPosisi();
    }//GEN-LAST:event_formWindowOpened

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        
        if(main.Global.indeksDialog >= 9) {
            ImageIcon introSceneBackground = main.Global.backgroundIntroScene2.ambilGambar(background);
            background.setIcon(introSceneBackground);
        }
        
//        if(main.Global.indeksDialog >= 16 && main.Global.indeksDialog < 20) {
//            
//        }
        if (main.Global.indeksDialog < main.Global.listBriefing.length - 1) {
            main.Global.indeksDialog++; // Naikkan indeks ke data berikutnya
            tampilkanDialogSekarang();    // Refresh teks di layar
    } else {
        // Jika dialog sudah habis semua, langsung pindah ke scene berikutnya
        script.Transisi.pindahScene(this, new scene.ThemeScreen.briefingScrene2());
    }
    }//GEN-LAST:event_mouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(introScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(introScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(introScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(introScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new introScene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel backgroundDialog;
    private javax.swing.JLabel backgroundSurat;
    private javax.swing.JTextArea boxDialog;
    private javax.swing.JLabel detektifSprite;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
