
package scene.HomeScreen;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.ImageIcon;
import main.main;


public class homeScreen extends javax.swing.JFrame {

    /**
     * Creates new form homeScreen
     */
    public homeScreen() {
        initComponents();
        
        
        this.getContentPane().setLayout(null);
        
        // TINGGAL PANGGIL SEPERTI INI:
        // Panggil object dari main, lalu suruh method ambilGambar mengurusi backgroundLabel ini
        ImageIcon icon = main.bgTangga.ambilGambar(background);
        ImageIcon detektif = main.guwe.ambilGambar(chara);
        
        background.setIcon(icon);
        background.setText("");
        
        chara.setIcon(detektif);
        chara.setText("");
        
        
        
        
//        try {
//    
//        java.net.URL urlTangga = getClass().getResource("/assets/background/tangga.jpg");
//        java.net.URL urlMutsukiHappy = getClass().getResource("/assets/character/mutsuki_happy.png");
//        java.net.URL urlTextBox = getClass().getResource("/assets/ui/dialog.png");
//    
//        if (urlTangga != null && urlMutsukiHappy != null ) {
//        ImageIcon iconTangga = new ImageIcon(urlTangga);
//        ImageIcon iconMutsukiHappy = new ImageIcon(urlMutsukiHappy);
//        ImageIcon iconTextBox = new ImageIcon(urlTextBox);
//        
//        Image imgMentah = iconTangga.getImage();
//        Image imgResize = imgMentah.getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
//        Image imgMentah2 = iconMutsukiHappy.getImage();
//        Image imgResize2 = imgMentah2.getScaledInstance(chara.getWidth(), chara.getHeight(), Image.SCALE_SMOOTH);
//        Image imgMentah3 = iconTextBox.getImage();
//        Image imgResize3 = imgMentah3.getScaledInstance(box.getWidth(), box.getHeight(), Image.SCALE_SMOOTH);
//        
//        background.setIcon(new ImageIcon(imgResize));
//        background.setText("");
//        
//        chara.setIcon(new ImageIcon(imgResize2));
//        chara.setText("");
//        
//        box.setIcon(new ImageIcon(imgResize3));
//        box.setText("Selamat siang, sensei");
//        
//        box.setHorizontalTextPosition(JLabel.CENTER); // Posisi teks di tengah secara horizontal
//        box.setVerticalTextPosition(JLabel.CENTER);   // Posisi teks di tengah secara vertical (di atas gambar)
//        
//    } else {
//        System.err.println("Gagal memuat gambar! File tangga.jpg tidak ditemukan di package.");
//    }
//} catch (Exception e) {
//    e.printStackTrace();
//}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JLabel();
        chara = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        box.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 1650, 360));
        getContentPane().add(chara, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 380, 770));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1887, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel box;
    private javax.swing.JLabel chara;
    // End of variables declaration//GEN-END:variables
}
